package nom;

public class Logical {
	public static void main(String[] args) {
		int a=6;
		int b=4;
		float g=6.6f;
		float h=3.3f;
		double i=7.13735678d;
		double j=2.3176578d;
		long c=765432110l;
		long d=32169823l;
		int radius=10;
		int rad=radius*radius;
		int r=10;
		int p=20;
		int q=r+p;
		int s=q/2;
		float n1=123.4f;
		float n2=27.78f;
		int s1=12;
		int s2=18;
		boolean isminor=s1<s2;
		int a1=2;
		int a2=3;
		int a3=4;
		int cubea1=a1*a1*a1;
		int cubea2=a2*a2*a2;
		int cubea3=a3*a3*a3;
		int f1=12;
		int f2=14;
		int f3=16;
		int f4=18;
		int f5=20;
		int total=f1+f2+f3+f4+f5;
		int average=total/5;
		int father=60;
		int son=30;
		int student1=45;
		int student2=35;
		int j1=12;
		int j2=13;
		int j3=18;
		int j4=j1*j2;
		int j5=j4+j3;
		int celcius=7;
		int fahrenhiet=celcius*9/5;
		int height=150;
		int weight=50;
		int q1=7;
		int q2=5;
		int q3=8;
		int q4=6;
		float m1=2.1678f;
		float m2=1.7315f;
		float m3=3.1731f;
		char v1='A';
		char v2='B';
		String r1="Technologies";
		String r2="good place to";
		String r3="java";
		String studentname="anbarasu";
		String initial="bg";
		String nameofstudent="anbarasu";
		String mobilenumber="7200283733";
		String student3="raja";
		String student4="roja";
		int rollno1=4001;
		int rollno2=4007;
		String personname="anbu";
		float height1=1.5f;
		int weight1=50;
		float height2=height1*height1;
		float bmi=weight1/height2;
		int t=16;
		int square=t*t;
		String dad="Gangadaran";
		int bb=20;
		int cc=0;
		boolean zeroornot=bb!=cc;
		String section="C";
		System.out.println(a+b);
		System.out.println(a-b);
		System.out.println(a*b);
		System.out.println(a/b);
		System.out.println(g+h);
		System.out.println(g-h);
		System.out.println(g*h);
		System.out.println(g/h);
		System.out.println(i+j);
		System.out.println(i-j);
		System.out.println(i*j);
		System.out.println(i/j);
		System.out.println(c-d);
		System.out.println(3.14*rad);
		System.out.println(s);
		System.out.println(n1*n2);
		System.out.println(isminor);
		System.out.println(cubea1);
		System.out.println(cubea2);
		System.out.println(cubea3);
		System.out.println(average);
		System.out.println(father-son);
		System.out.println(student1-student2);
		System.out.println(j5);
		System.out.println(fahrenhiet+32);
		System.out.println("person height "+height);
		System.out.println("person weight "+weight);
		System.out.println((q1+q2)*(q1+q2));
		System.out.println((q3-q4)*(q3-q4));
		System.out.println("Onesoft "+r1+" is the "+r2+" learn "+r3);
		System.out.println(m1+m2+m3);
		System.out.println(studentname+" "+initial);
		System.out.println(nameofstudent+" "+mobilenumber);
		System.out.println(student3+" "+rollno1);
		System.out.println(student4+" "+rollno2);
		System.out.println(personname+" bmi "+bmi);
		System.out.println(square);
		System.out.println("Anbarasu "+dad);
		System.out.println(zeroornot);
		System.out.println("Varun 10th "+section);
		System.out.println(v1+v2);
	}

}
